apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: qa-
resources:
  - ../../base

images:
  - name: my-app
    newTag: "1.0-qa"

replicas:
  - name: my-app
    count: 1

configMapGenerator:
  - name: qa-config
    literals:
      - ENV=qa
