apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: pro-
resources:
  - ../../base

images:
  - name: my-app
    newTag: "1.0-pro"

replicas:
  - name: my-app
    count: 1

configMapGenerator:
  - name: pro-config
    literals:
      - ENV=pro
