apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/dariasmoises979-blip/pipeline-build.git' # Cambia por tu repo
    targetRevision: HEAD
    path: kubernetes/test/app-01
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
