apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helloworld.fullname" . }}-config
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
data:
  APP_MESSAGE: {{ .Values.config.APP_MESSAGE | quote }}
