apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helloworld.fullname" . }}-secret
  labels:
    {{- include "helloworld.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_SECRET: {{ .Values.secret.APP_SECRET | quote }}
