apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: staging-
resources:
  - ../../base

images:
  - name: my-app
    newTag: "1.0-staging"

replicas:
  - name: my-app
    count: 1

configMapGenerator:
  - name: staging-config
    literals:
      - ENV=staging
