# ==========================================================
# 游빐 Despliegue de Argo CD en Google Kubernetes Engine (GKE)
# ==========================================================
# Archivo: values.yaml
# Descripci칩n:
#   Este archivo define la configuraci칩n de Argo CD desplegado en un cl칰ster GKE,
#   utilizando un Ingress p칰blico con HTTPS gestionado por GCE.
#
# Variables principales:
#   - global.image.tag: versi칩n de la imagen de Argo CD
#   - server.service.type: tipo de servicio Kubernetes (LoadBalancer recomendado para GKE)
#   - server.ingress.*: configuraci칩n de ingreso HTTP/HTTPS
#   - configs.params.*: par치metros del servidor Argo CD (modo inseguro, root path, etc.)
#   - extraObjects: certificados y dominios gestionados opcionales (ManagedCertificate)
#
# Requisitos:
#   - Cl칰ster GKE con Ingress Controller (GCE Ingress habilitado)
#   - Dominio y certificado gestionado (opcional)
# ==========================================================

global:
  image:
    tag: v2.13.0   # 游빌 Versi칩n de Argo CD (verifica compatibilidad con helm chart)

server:
  # ======================================================
  # 丘뙖잺 Configuraci칩n del servicio de Argo CD
  # ======================================================
  service:
    type: LoadBalancer     # LoadBalancer requerido para Ingress GCE externo
    servicePortHttp: 80    # Puerto HTTP interno
    servicePortHttps: 443  # Puerto HTTPS interno

  # ======================================================
  # 游깷 Ingress p칰blico (opcional)
  # ======================================================
  # Descomenta este bloque si quieres usar Ingress gestionado por GCE
  #
  # ingress:
  #   enabled: true
  #   ingressClassName: "gce"   # Clase de Ingress (GCE para externo)
  #   hostname: "argocd.midominio.com"   # Dominio p칰blico asignado
  #   path: /
  #   pathType: Prefix
  #   tls: true
  #   annotations:
  #     kubernetes.io/ingress.class: "gce"
  #     kubernetes.io/ingress.global-static-ip-name: "argocd-static-ip"  # IP reservada opcional
  #     networking.gke.io/managed-certificates: "argocd-cert"
  #     kubernetes.io/ingress.allow-http: "false"

configs:
  params:
    # ======================================================
    # 游댏 Par치metros del servidor Argo CD
    # ======================================================
    # Habilita el modo inseguro (solo para entornos de prueba)
    server.insecure: "true"

    # Habilita un rootpath personalizado (칰til si ArgoCD se expone bajo un subpath)
    # server.rootpath: "/argocd"

# ======================================================
# 游댎 Certificados y objetos extra (opcional)
# ======================================================
# Define un certificado gestionado por GCP para HTTPS autom치tico.
# Este recurso solo aplica si usas Ingress con GCE.
#
# extraObjects:
#   - apiVersion: networking.gke.io/v1
#     kind: ManagedCertificate
#     metadata:
#       name: argocd-cert
#     spec:
#       domains:
#         - argocd.midominio.com
