name: Reusable Date Workflow

on:
  workflow_call:
    inputs:
      timezone:
        description: 'Timezone for date (e.g., Europe/Madrid)'
        required: false
        type: string
        default: 'UTC'
    outputs:
      current_date:
        description: 'The current date'
        value: ${{ jobs.show-date.outputs.date }}

jobs:
  docker:
          needs: build-test
          runs-on: ubuntu-latest
          steps:
            - name: Checkout del código
              uses: actions/checkout@v4
  
            - name: Checkout otro repositorio
              uses: actions/checkout@v4
              with:
                repository: dariasmoises979-blip/app
                path: app/local
                token: ${{ secrets.GITHUB_TOKEN }} 
                working-directory: local

            - name: Ver contenido del otro repo
              run: |
                  echo "Contenido de otro-repo:"
                  ls -la
                  
            - name: Login en Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
                logout: true              
      
            - name: Construir y publicar imagen (con cache y tag dinámico)
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: |
                  ${{ secrets.DOCKERHUB_USERNAME }}/flask-info-app:latest
                  ${{ secrets.DOCKERHUB_USERNAME }}/flask-info-app:${{ github.sha }}
                cache-from: type=gha
                cache-to: type=gha,mode=max
               