name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - qa
      - pro
  pull_request:
    branches:
      - main
      - qa
      - pro

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TF_LOG: "INFO"

    strategy:
      matrix:
        env: [qa, pro]

    steps:
      # 1️⃣ Checkout del repo
      - uses: actions/checkout@v3

      # 2️⃣ Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      # 3️⃣ Instalar TFLint
      - name: Install TFLint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      # 4️⃣ Inicializar Terraform con backend remoto
      - name: Terraform Init
        working-directory: terraform/${{ matrix.env }}
        run: terraform init

      # 5️⃣ Validar sintaxis y linter
      - name: Terraform Validate & TFLint
        working-directory: terraform/${{ matrix.env }}
        run: |
          terraform validate
          tflint

      # 6️⃣ Generar plan
      - name: Terraform Plan
        working-directory: terraform/${{ matrix.env }}
        run: terraform plan -out=tfplan

      # 7️⃣ Aplicar cambios solo en main branch
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        working-directory: terraform/${{ matrix.env }}
        run: terraform apply -auto-approve "tfplan"
